//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blog.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post
    {
        public int id { get; set; }
        public int idUser { get; set; }
        public int idCategory { get; set; }
        public string synopsis { get; set; }
        public string postContent { get; set; }
        public System.DateTime created { get; set; }
        public string title { get; set; }
    
        public virtual Category Category { get; set; }
        public string UserName { get; set; }
    }
}
